### ISSUE TITLE
Trigger Specific Job based on Payload

### ISSUE THREAD

**Issue by karthickrc** [jenkinsci/generic-webhook-trigger-plugin#52]
The plugin works great. Let say I have 5 jobs using this plugin.  Instead of triggering all the jobs can I control based on the event /payload I receive?

Also, does this plugin execution can handle huge list of events fired ( example: 100 in a min) ? 

If the plugin does not lose the received payload during heavy load, can I see the pending requests in Jenkins/ Plugin configuration?

Once again thanks

**Comment by tomasbjerre** [comment]
Nice to see that it works for you =)

If the invoking system knows what job to triggen, then best way is to use an authentication token. And have a different tokens for each job. So that only the job that is intended to trigger will be visible for that request. That will give the best performance.

I have been thinking about adding option to not flattern the json structure, that would also help performance.
