### ISSUE TITLE
When building using a token, the cause parameter has no effect

### ISSUE THREAD

**Issue by berthamilton** [jenkinsci/generic-webhook-trigger-plugin#57]
When you build using a token (i.e. JENKINS_URL/job/my_job/build?token=sometoken&cause=The+Cause) the build lists the cause as "Started by remote host 127.0.0.1 with note: The Cause"

When you trigger a build via a webhook (i.e. JENKINS_URL/generic-webhook-trigger/invoke?token=sometoken&cause=The+Cause) the cause is always "Generic Cause"

Is it possible to pass the cause parameter through so it can be shown with the build as the reason the build was triggered?

Thank you

**Comment by tomasbjerre** [comment]
Absolutely!

1. It can be implemented as a configuration in the job. A text field where the user can enter a text, and use variables. So that the job can be configured with something like ´Job was triggered becasye ${username} pushed commit {commitId}´.

2. Or, it can be implemented as using the `cause` parameter from the query parameters.

I think I like 1 best. And if someone wants 2, then they can just set `${cause}` in the new text-field in job configuration.

**Comment by berthamilton** [comment]
Thanks for replying. I'm not certain what you mean. Is there currently a way to use a text field to set this "Generic Cause" message that appears on the UI for each build?

![screenshot 2018-04-18 10 37 41](https://user-images.githubusercontent.com/1256277/38924341-9e77c274-42f4-11e8-9e04-a8f62e4374f2.png)

Thanks

**Comment by tomasbjerre** [comment]
No it is not implemented. But I'll probably have time to add it later today.

Den ons 18 apr. 2018 11:40Rob Hamilton <notifications@github.com> skrev:

**Comment by tomasbjerre** [comment]
I'm releasing 1.32 now with this feature added. There is now a "cause" option in the configuration of the job.

Will be available in the update site within a few hours.

Open issue again if not working.
